#!/bin/bash
# tray-icon for VirtualBox
# 'yad'(zenity like) is needed

TMP_FILE="/tmp/vm_list"
VBOX="/usr/bin/VirtualBox"
VBOXMANAGE="/usr/bin/vboxmanage"
VBOX_ICON="/usr/share/pixmaps/virtualbox.png"

"${VBOXMANAGE}" list -l vms | sed '/USB Device/,/Configured/ d' | sed -n '/Name:  /s/Name:\s*//p;/Guest OS/s/Guest OS:\s*//p' | sed '$!N;s/\n/%/' > "${TMP_FILE}"

##### CREATION DE L'ICONE DE NOTIFICATION
PIPE="/tmp/${0##*/}-$$-pipe"
mkfifo ${PIPE}
exec 3<> ${PIPE}

yad --notification \
    --listen \
    --image="${VBOX_ICON}" \
    --text="Launch a VirtualBox guest host" \
    --item-separator ":" \
    --command="${VBOX}" 2>/dev/null <&3 & pid="$!"

sleep 1

##### TRAY MENU
TRAY_MENU_HEAD='menu:Guest hosts list'
TRAY_SEP=""
# SET 'THE GUEST HOSTS' MENU
NUM=0
while read line
do
    NUM=$((NUM+1))
    NAME=$(echo $line | cut -d'%' -f1)
    OS=$(echo $line | cut -d'%' -f2)
    
    case $OS in
        Linux*)
                PNG="linux-logo" #
                ;;
        Ubuntu*)
                PNG="ubuntu" #
                ;;
        Debian*)
                PNG="debian" #
                ;;
        Red\ Hat*)
                PNG="redhat" #
                ;;
        openSuse*)
                PNG="opensuse" #
                ;;
        Turbolinux*)
                PNG="turbolinux" #
                ;;
        Mandriva*)
                PNG="mandriva" #
                ;;
        Gentoo*)
                PNG="gentoo" #
                ;;
        Fedora*)
                PNG="fedora" #
                ;;
        Xandros*)
                PNG="xandros" #
                ;;
        Oracle\ \(*)
                PNG="oraclelinux" #
                ;;
        Other\ Linux*)
                PNG="linux-logo" #
                ;;
        Windows\ 7*)
                PNG="win7" #
                ;;
        Windows\ 8*)
                PNG="win8" #
                ;;
        Windows\ 8.1*)
                PNG="win8.1" #
                ;;
        Windows\ 10*)
                PNG="win10" #
                ;;
        Windows\ XP*)
                PNG="winlogo" #
                ;;
        Mac\ OS\ X*)
                PNG="osx" #
                ;;
        FreeBSD*)
                PNG="freebsd" #
                ;;
        OpenBSD*)
                PNG="openbsd" #
                ;;
        NetBSD*)
                PNG="netbsd" #
                ;;
        *Solaris*)
                PNG="solaris" #
                ;;
        *OS\/2*)
                PNG="os2" #
                ;;
        eComStation*)
                PNG="ecomstation" #
                ;;
        DOS*)
                PNG="dos" #
                ;;
        Netware*)
                PNG="netware" #
                ;;
        *)
                PNG="gtk-help" #
                ;;
    esac
    
    ### DYNAMIQUE VARS !!!
    declare "TRAY_MENU_${NUM}=$NAME:'${VBOX}' --startvm '$NAME':${PNG}"
    var="TRAY_MENU_$NUM"
    TRAY_MENU_LIST="${TRAY_MENU_LIST}|${!var}"
    #echo $NAME -- $OS -- $PNG # DEBUG
done < "${TMP_FILE}"

TRAY_MENU_QUIT="Quit:quit:stock_exit"
echo "${TRAY_MENU_HEAD}|${TRAY_SEP}${TRAY_MENU_LIST}|${TRAY_MENU_QUIT}" >&3
##### /TRAY MENU
